

> Import libraries to use



In [ ]:
import numpy as np

>  # Introduction to numpy (Skip if you already are familiar)

>> Creating a 1D array

In [ ]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


>> Creating a 2D array


In [ ]:
a = np.array([[1,2],[3,4]])
print(a)

[[1 2]
 [3 4]]


>> Creating an array full of zeros


In [ ]:
a = np.zeros(shape=(10))
print(a)
a = np.zeros(shape=(5,2))
print(a)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


>> Infinity in numpy

In [ ]:
print(np.inf)

inf


>> Max and Argmax

In [ ]:
a = np.array([2,1,4,3])
print(np.max(a))
print(np.argmax(a))

4
2


>> From list to Numpy

In [ ]:
l = [1,2,3,4]
print(l)
print(np.asarray(l))

[1, 2, 3, 4]
[1 2 3 4]


>> Random in numpy

In [ ]:
# Array of Random integers ranging from 1 to 10 (with any size you want)
a = np.random.randint(low=1, high=10, size=(5,2))
print(a)

# Array of random elements of a list with any size you want
a = np.random.choice([0,1,2], size=(2,))

[[6 4]
 [1 6]
 [7 5]
 [5 9]
 [4 2]]


>> Shapes in numpy

In [ ]:
a = np.random.randint(low=1, high=5, size=(4,2))
print(a.shape)
print(a)

# Reshape a to a vector of shape = (8,1)
a = a.reshape((8,1))
print(a.shape)
print(a)

(4, 2)
[[4 3]
 [3 2]
 [2 3]
 [2 2]]
(8, 1)
[[4]
 [3]
 [3]
 [2]
 [2]
 [3]
 [2]
 [2]]


# Pre-defined utilities

In [ ]:

int_to_char = {
    0 : 'u',
    1 : 'r',
    2 : 'd',
    3 : 'l'
}

policy_one_step_look_ahead = {
    0 : [-1,0],
    1 : [0,1],
    2 : [1,0],
    3 : [0,-1]
}

def policy_int_to_char(pi,n):

    pi_char = ['']

    for i in range(n):
        for j in range(n):

            if i == 0 and j == 0 or i == n-1 and j == n-1:

                continue

            pi_char.append(int_to_char[pi[i,j]])

    pi_char.append('')

    return np.asarray(pi_char).reshape(n,n)

# 1- Policy evaluation

In [ ]:
def policy_evaluation(n,pi,v,Gamma,threshhold):
  """
    This function should return the value function that follows the policy pi.
    Use the stopping criteria given in the problem statement.
  """

# 2- Policy improvement

In [ ]:
def policy_improvement(n,pi,v,Gamma):
  """
    This function should return the new policy by acting in a greedy manner.
    The function should return as well a flag indicating if the output policy
    is the same as the input policy.

    Example:
      return new_pi, True if new_pi = pi for all states
      else return new_pi, False

    Parameters:
    - n (int): Number of states
    - pi (list): Current policy, list where each element is the action for each state
    - v (list): Current value function for each state
    - Gamma (float): Discount factor

    Returns:
    - new_pi (list): Updated policy
    - is_policy_stable (bool): True if the new policy is the same as the input policy, False otherwise
  """
  new_pi = pi[:]
    is_policy_stable = True

    for state in range(n):
        # Assuming we have a function `action_values(state, v, Gamma)` that calculates
        # the value for each possible action in the given state based on `v` and `Gamma`.
        # This would return a list of values for each action.

        action_values = [sum([prob * (reward + Gamma * v[next_state])
                              for prob, next_state, reward in transitions])
                         for transitions in get_possible_transitions(state)]

        # Find the action with the maximum value
        best_action = max(range(len(action_values)), key=lambda a: action_values[a])

        # If the best action is different from the current policy action, update it
        if pi[state] != best_action:
            is_policy_stable = False
            new_pi[state] = best_action

    return new_pi, is_policy_stable

# 3- Policy Initialization

In [ ]:
import random

def policy_initialization(n, num_actions):
    """
    This function returns an initial random policy for all states.

    Parameters:
    - n (int): Number of states
    - num_actions (int): Number of possible actions in each state

    Returns:
    - list: A list where each element is an action (0 to num_actions-1) for each state
    """
    return [random.randint(0, num_actions - 1) for _ in range(n)]


# 4- Policy Iteration algorithm

In [ ]:
def policy_iteration(n,Gamma,threshhold):

    pi = policy_initialization(n=n)

    v = np.zeros(shape=(n,n))

    while True:

        v = policy_evaluation(n=n,v=v,pi=pi,threshhold=threshhold,Gamma=Gamma)

        pi , pi_stable = policy_improvement(n=n,pi=pi,v=v,Gamma=Gamma)

        if pi_stable:

            break

    return pi , v

# Main Code to Test

In [ ]:
n = 4

Gamma = [0.8,0.9,1]

threshhold = 1e-4

for _gamma in Gamma:

    pi , v = policy_iteration(n=n,Gamma=_gamma,threshhold=threshhold)

    pi_char = policy_int_to_char(n=n,pi=pi)

    print()
    print("Gamma = ",_gamma)

    print()

    print(pi_char)

    print()
    print()

    print(v)



Gamma =  0.8

[['' 'l' 'l' 'd']
 ['u' 'u' 'u' 'd']
 ['u' 'u' 'r' 'd']
 ['u' 'r' 'r' '']]


[[ 0.   -1.   -1.8  -2.44]
 [-1.   -1.8  -2.44 -1.8 ]
 [-1.8  -2.44 -1.8  -1.  ]
 [-2.44 -1.8  -1.    0.  ]]

Gamma =  0.9

[['' 'l' 'l' 'd']
 ['u' 'u' 'u' 'd']
 ['u' 'u' 'r' 'd']
 ['u' 'r' 'r' '']]


[[ 0.   -1.   -1.9  -2.71]
 [-1.   -1.9  -2.71 -1.9 ]
 [-1.9  -2.71 -1.9  -1.  ]
 [-2.71 -1.9  -1.    0.  ]]

Gamma =  1

[['' 'l' 'l' 'd']
 ['u' 'u' 'u' 'd']
 ['u' 'u' 'r' 'd']
 ['u' 'r' 'r' '']]


[[ 0. -1. -2. -3.]
 [-1. -2. -3. -2.]
 [-2. -3. -2. -1.]
 [-3. -2. -1.  0.]]
